name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'
  workflow_dispatch:

env:
  BINARY_PREFIX: "BFV-WTC_"
  BINARY_SUFFIX: ""
  COMMIT_ID: "${{ github.sha }}"
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is trigged by pull request."

jobs:
  build:
    name: Build binary CI
    runs-on: windows-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Build binary file
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          IS_PR: ${{ !!github.head_ref }}
        run: |
          $env:BINARY_SUFFIX = ".exe"
          echo $env:PR_PROMPT
          $env:CGO_ENABLED = 1
          $env:BINARY_NAME = "$env:BINARY_PREFIX$env:GOOS_$env:GOARCH$env:BINARY_SUFFIX"
          $env:LD_FLAGS = "-s -w -X main.Version=$($env:COMMIT_ID.Substring(0,7))"
          go mod tidy
          go build -o "output/$env:BINARY_NAME" -trimpath -ldflags "$env:LD_FLAGS" .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: output/
